version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5344:1433"
    volumes:
      - corretora-sqldata:/var/opt/mssql

volumes:
  corretora-sqldata:
    external: false
